// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiGeP.Model;

#nullable disable

namespace SiGeP.Model.Migrations
{
    [DbContext(typeof(DbModelContext))]
    partial class DbModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiGeP.Model.Model.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 499, DateTimeKind.Local).AddTicks(1266),
                            CreatedBy = "System",
                            DeletedBy = "",
                            Name = "admin",
                            Password = "admin",
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("SiGeP.Model.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CUIL")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("VARCHAR");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.HasIndex("GenderId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CUIL = "20123456789",
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(1923),
                            CreatedBy = "System",
                            DeletedBy = "",
                            GenderId = 1,
                            Name = "Juan Pérez",
                            Phone = "1234567890",
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CUIL = "20234567890",
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(1940),
                            CreatedBy = "System",
                            DeletedBy = "",
                            GenderId = 2,
                            Name = "María López",
                            Phone = "0987654321",
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1982, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CUIL = "20345678901",
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(1942),
                            CreatedBy = "System",
                            DeletedBy = "",
                            GenderId = 1,
                            Name = "Carlos García",
                            Phone = "1122334455",
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1995, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CUIL = "20456789012",
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(1943),
                            CreatedBy = "System",
                            DeletedBy = "",
                            GenderId = 2,
                            Name = "Ana Martínez",
                            Phone = "6677889900",
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1978, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CUIL = "20567890123",
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(1978),
                            CreatedBy = "System",
                            DeletedBy = "",
                            GenderId = 1,
                            Name = "Miguel Fernández",
                            Phone = "5566778899",
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("SiGeP.Model.Model.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(2103),
                            CreatedBy = "System",
                            DeletedBy = "",
                            Name = "Femenino",
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(2104),
                            CreatedBy = "System",
                            DeletedBy = "",
                            Name = "Masculino",
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 8, 18, 13, 21, 35, 498, DateTimeKind.Local).AddTicks(2106),
                            CreatedBy = "System",
                            DeletedBy = "",
                            Name = "Otro",
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("SiGeP.Model.Model.Customer", b =>
                {
                    b.HasOne("SiGeP.Model.Model.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
